### ISSUE TITLE
UI Attach runs into error

### ISSUE THREAD

**Issue by Huluk** [neovim/neovim-ruby#101]
I'm trying to make an UI attachment in a plugin, but it doesn't seem to work and runs into errors.
I tried various different variations of the code below:

```ruby
Neovim.logger << 'test!'

Neovim.plugin do |plug|
  plug.ui_attach(999, 999, {}) do |*a|
    Neovim.logger << a.inspect
  end
end
```

With and without block argument, with value in the hashmap and entirely without a third argument, but I'm always getting the same error, so I suspect that it's a plugin issue. Otherwise any hints are welcome.

The error appears once I call `:UpdateRemotePlugins` (I'm using https://github.com/junegunn/vim-plug).

## Versions
macOS 14.1.1 Sonoma
Ruby: 3.2.2 (rbenv 1.2.0)
Gem: 3.4.12
Neovim-Ruby: 0.9.1
Neovim: 0.9.4

## Neovim error message
```
function remote#host#UpdateRemotePlugins[6]..<SNR>61_RegistrationCommands[15]..remote#
host#Require[10]..provider#ruby#Require[8]..provider#Poll, line 7
Vim(if):Error invoking 'poll' on channel 5:^@Invalid channel: 5
function remote#host#UpdateRemotePlugins[6]..<SNR>61_RegistrationCommands[15]..remote#
host#Require[10]..provider#ruby#Require[8]..provider#Poll, line 17
Failed to load ruby host. You can try to see what happened by starting nvim with $NVIM
_RUBY_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
remote/host: generated rplugin manifest: /Users/huluk/.local/share/nvim/rplugin.vim
```

## Error logs
```
# Logfile created on 2023-11-25 17:07:28 +0100 by logger.rb/v1.5.3
{"_level":"DEBUG","_time":"2023-11-25T17:07:28.708601","_class":"Neovim::EventLoop","_method":"run","exception":"EOFError","message":"end of file reached"}
{"_level":"DEBUG","_time":"2023-11-25T17:07:28.720948","_class":"Neovim::EventLoop","_method":"run","exception":"EOFError","message":"end of file reached","backtrace":["/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/connection.rb:47:in `readpartial'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/connection.rb:47:in `read'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/connection.rb:47:in `read'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:109:in `read'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:80:in `block in run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:75:in `loop'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:75:in `run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/session.rb:35:in `run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/host.rb:29:in `run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/host.rb:17:in `run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/host/cli.rb:33:in `run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/exe/neovim-ruby-host:5:in `<top (required)>'","/usr/local/var/rbenv/versions/3.2.2/bin/neovim-ruby-host:25:in `load'","/usr/local/var/rbenv/versions/3.2.2/bin/neovim-ruby-host:25:in `<main>'"]}
test!
```

**Comment by alexgenco** [comment]
I think there are a couple things causing this... first of all it seems like writing to `Neovim.logger` from a remote plugin breaks the rpc connection. Try removing those lines that write to the logger.

The next thing you're going to run into though, is that you're calling `ui_attach` on the remote plugin DSL object, not a neovim client. I think this closer to what you want, although I'm not sure if this works either:

```ruby
Neovim.plugin do |plug|
  plug.command(:StartMyUI) do |client|
    client.ui_attach(999, 999, {})
  end
end
```

That said, I'm not sure if you want to spawn a UI within a remote plugin like this... I'm pretty unfamiliar with writing UI clients but my understanding was that the UI process should be responsible for starting an embedded nvim process, which it sends the `nvim_ui_attach` rpc when it's ready to draw (see docs: https://neovim.io/doc/user/ui.html). Maybe @justinmk could point to better resources/examples? Sorry I'm not super helpful here.

**Comment by Huluk** [comment]
Thank you for the hints, and the quick reply!

With your code snippet, at least it doesn't crash any more. Not sure yet if it's working, I'll do some more experiments later.

I _think_ I'm fine with my plugin attaching to the UI. I don't want to embed vim somewhere, I want to produce output on an additional channel for an existing vim instance. (To be concrete, I want to pipe command output into a text to speech engine, in addition to the output which shows on the screen).

I guess after my client calls `ui_attach` with `{ext_cmdline: true, ext_messages: true}`, I now want to add a listener to `msg_show` somehow.

Once I have a working example, I might make a pull request with documentation updates – I must admit I'm really struggling to get started here. Trying to look at other projects either using `neovim-ruby` or other language interfaces, but it's really hard to find the right info. Not a complaint, I know how much work it is :D

**Comment by Huluk** [comment]
`ui_attach` seems to work – the plugin shows up for `:echo nvim_list_uis()`. I'm now trying to actually listen to events. For my experiments, I picked "option_set", since that is part of the always-on global set and I should be able to trigger it with `:set showtabline=0`. But how do I actually register a callback for this? `client.subscribe` does not take any block arguments.

The following code doesn't work, but also I'd be very surprised if I'm even going in the correct direction:
```ruby
Neovim.plugin do |plug|

  p = plug.instance_variable_get(:@plugin)
  # initialize(source, type, name, sync, options, block)
  option_set_handler = Neovim::Plugin::Handler.new(
    nil,
    :event,
    'option_set',
    false,
    {},
    Proc.new { |*args| system 'say', 'this is a test!' + args.inspect }
  )
  p.handlers.push(option_set_handler)

  plug.command(:Start) do |client|
    client.subscribe(:option_set)
    client.ui_attach(999, 999, {ext_cmdline: true, ext_messages: true})
    client.subscribe(:option_set)
  end
end
```

**Comment by justinmk** [comment]
> But how do I actually register a callback for this? `client.subscribe` does not take any block arguments.

subscribe() is kinda useless. After you ui_attach, all UI events will be sent to the channel as `redraw` events. `:help ui-events` explains more and shows an example.
